-- Create Table
create table frames (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  url text not null
);

-- Setup Storage
insert into storage.buckets (id, name, public) values ('frames', 'frames', true);

-- RLS Policies
create policy "Public Access" on storage.objects for select using ( bucket_id = 'frames' );
create policy "Public Upload" on storage.objects for insert with check ( bucket_id = 'frames' );
create policy "Public Delete" on storage.objects for delete using ( bucket_id = 'frames' );
